name: godevi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.3

  get_cli: ^1.8.1
  get: 4.6.5
  font_awesome_flutter: ^10.2.1
  smooth_star_rating: ^1.1.1
  flutter_page_indicator: ^0.0.3
  intl: ^0.17.0
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  get_storage: ^2.0.3
  mixins: ^0.0.7
  flutter_easyloading: ^3.0.3
  teledart: ^0.3.4


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700